# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logdgev <- function(x, mu, sigma, xi) {
    .Call('_GEVSSVS_logdgev', PACKAGE = 'GEVSSVS', x, mu, sigma, xi)
}

logdnorm <- function(x, var) {
    .Call('_GEVSSVS_logdnorm', PACKAGE = 'GEVSSVS', x, var)
}

MuSigmaUpdate <- function(x, mu, Sigma, n) {
    .Call('_GEVSSVS_MuSigmaUpdate', PACKAGE = 'GEVSSVS', x, mu, Sigma, n)
}

logfall <- function(T, p, x, Y, X, prior) {
    .Call('_GEVSSVS_logfall', PACKAGE = 'GEVSSVS', T, p, x, Y, X, prior)
}

rwBmetropolis <- function(x, sd, T, p, Y, X, prior) {
    .Call('_GEVSSVS_rwBmetropolis', PACKAGE = 'GEVSSVS', x, sd, T, p, Y, X, prior)
}

